### ISSUE TITLE
Error: Running the application

### ISSUE THREAD

**Issue by akolnati** [meteor-space/todos#3]
Application missing package space:domain. Is this package removed from atmospherejs?

**Comment by rhyslbw** [comment]
Hi @AdityaDinesh 

It's currently pre-release, and hasn't been an issue for us as we use [mgp](https://github.com/DispatchMe/mgp) for development.

I'll publish to atmosphere now though.

**Comment by rhyslbw** [comment]
On second thought I'm going to hold on this as there are other pre-release dependencies, so you will still need to use mgp. We're working on the next major Space package versions so breaking changes mean we can't publish incrementally.

It's really simple to use, just install the mgp npm package on your machine and run the `mgp` command in the todos root directory. It's the bleeding edge, but right now to see the latest work checkout `feature/basic-elements-of-ui-layer`. Feel free to jump into the [Gitter room](https://gitter.im/meteor-space/general?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you need assistance :-)
